[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[dependencies]
bsky_core = { path = "../core" }
jetstream = { path = "../jetstream" }
tracing = { workspace = true }
sqlx = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
chrono = { workspace = true }
cid = { workspace = true }
serde_json = { workspace = true }
